// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/openaiwebthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OpenAIWebThreadCreate is the builder for creating a OpenAIWebThread entity.
type OpenAIWebThreadCreate struct {
	config
	mutation *OpenAIWebThreadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *OpenAIWebThreadCreate) SetUserID(v int64) *OpenAIWebThreadCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OpenAIWebThreadCreate) SetGroupID(v int64) *OpenAIWebThreadCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIWebThreadCreate) SetAccountID(v int64) *OpenAIWebThreadCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetLocalThreadID sets the "local_thread_id" field.
func (_c *OpenAIWebThreadCreate) SetLocalThreadID(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetLocalThreadID(v)
	return _c
}

// SetPageSessionID sets the "page_session_id" field.
func (_c *OpenAIWebThreadCreate) SetPageSessionID(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetPageSessionID(v)
	return _c
}

// SetUpstreamConversationID sets the "upstream_conversation_id" field.
func (_c *OpenAIWebThreadCreate) SetUpstreamConversationID(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetUpstreamConversationID(v)
	return _c
}

// SetNillableUpstreamConversationID sets the "upstream_conversation_id" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableUpstreamConversationID(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetUpstreamConversationID(*v)
	}
	return _c
}

// SetUpstreamSessionID sets the "upstream_session_id" field.
func (_c *OpenAIWebThreadCreate) SetUpstreamSessionID(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetUpstreamSessionID(v)
	return _c
}

// SetNillableUpstreamSessionID sets the "upstream_session_id" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableUpstreamSessionID(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetUpstreamSessionID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *OpenAIWebThreadCreate) SetProvider(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableProvider(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *OpenAIWebThreadCreate) SetTitle(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableTitle(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *OpenAIWebThreadCreate) SetRequestedModel(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableRequestedModel(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetRequestedModel(*v)
	}
	return _c
}

// SetCapabilityMode sets the "capability_mode" field.
func (_c *OpenAIWebThreadCreate) SetCapabilityMode(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetCapabilityMode(v)
	return _c
}

// SetNillableCapabilityMode sets the "capability_mode" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableCapabilityMode(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetCapabilityMode(*v)
	}
	return _c
}

// SetHistoryMode sets the "history_mode" field.
func (_c *OpenAIWebThreadCreate) SetHistoryMode(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetHistoryMode(v)
	return _c
}

// SetNillableHistoryMode sets the "history_mode" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableHistoryMode(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetHistoryMode(*v)
	}
	return _c
}

// SetCachePolicy sets the "cache_policy" field.
func (_c *OpenAIWebThreadCreate) SetCachePolicy(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetCachePolicy(v)
	return _c
}

// SetNillableCachePolicy sets the "cache_policy" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableCachePolicy(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetCachePolicy(*v)
	}
	return _c
}

// SetSyncStatus sets the "sync_status" field.
func (_c *OpenAIWebThreadCreate) SetSyncStatus(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetSyncStatus(v)
	return _c
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableSyncStatus(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetSyncStatus(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OpenAIWebThreadCreate) SetStatus(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableStatus(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *OpenAIWebThreadCreate) SetLastSyncedAt(v time.Time) *OpenAIWebThreadCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableLastSyncedAt(v *time.Time) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *OpenAIWebThreadCreate) SetLastError(v string) *OpenAIWebThreadCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableLastError(v *string) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIWebThreadCreate) SetCreatedAt(v time.Time) *OpenAIWebThreadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableCreatedAt(v *time.Time) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIWebThreadCreate) SetUpdatedAt(v time.Time) *OpenAIWebThreadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OpenAIWebThreadCreate) SetDeletedAt(v time.Time) *OpenAIWebThreadCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OpenAIWebThreadCreate) SetNillableDeletedAt(v *time.Time) *OpenAIWebThreadCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OpenAIWebThreadCreate) SetUser(v *User) *OpenAIWebThreadCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *OpenAIWebThreadCreate) SetGroup(v *Group) *OpenAIWebThreadCreate {
	return _c.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *OpenAIWebThreadCreate) SetAccount(v *Account) *OpenAIWebThreadCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the OpenAIWebThreadMutation object of the builder.
func (_c *OpenAIWebThreadCreate) Mutation() *OpenAIWebThreadMutation {
	return _c.mutation
}

// Save creates the OpenAIWebThread in the database.
func (_c *OpenAIWebThreadCreate) Save(ctx context.Context) (*OpenAIWebThread, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIWebThreadCreate) SaveX(ctx context.Context) *OpenAIWebThread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIWebThreadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIWebThreadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIWebThreadCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := openaiwebthread.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := openaiwebthread.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		v := openaiwebthread.DefaultRequestedModel
		_c.mutation.SetRequestedModel(v)
	}
	if _, ok := _c.mutation.CapabilityMode(); !ok {
		v := openaiwebthread.DefaultCapabilityMode
		_c.mutation.SetCapabilityMode(v)
	}
	if _, ok := _c.mutation.HistoryMode(); !ok {
		v := openaiwebthread.DefaultHistoryMode
		_c.mutation.SetHistoryMode(v)
	}
	if _, ok := _c.mutation.CachePolicy(); !ok {
		v := openaiwebthread.DefaultCachePolicy
		_c.mutation.SetCachePolicy(v)
	}
	if _, ok := _c.mutation.SyncStatus(); !ok {
		v := openaiwebthread.DefaultSyncStatus
		_c.mutation.SetSyncStatus(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := openaiwebthread.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := openaiwebthread.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaiwebthread.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaiwebthread.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIWebThreadCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OpenAIWebThread.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "OpenAIWebThread.group_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIWebThread.account_id"`)}
	}
	if _, ok := _c.mutation.LocalThreadID(); !ok {
		return &ValidationError{Name: "local_thread_id", err: errors.New(`ent: missing required field "OpenAIWebThread.local_thread_id"`)}
	}
	if v, ok := _c.mutation.LocalThreadID(); ok {
		if err := openaiwebthread.LocalThreadIDValidator(v); err != nil {
			return &ValidationError{Name: "local_thread_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.local_thread_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PageSessionID(); !ok {
		return &ValidationError{Name: "page_session_id", err: errors.New(`ent: missing required field "OpenAIWebThread.page_session_id"`)}
	}
	if v, ok := _c.mutation.PageSessionID(); ok {
		if err := openaiwebthread.PageSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "page_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.page_session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamConversationID(); ok {
		if err := openaiwebthread.UpstreamConversationIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_conversation_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.upstream_conversation_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamSessionID(); ok {
		if err := openaiwebthread.UpstreamSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.upstream_session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OpenAIWebThread.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := openaiwebthread.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "OpenAIWebThread.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := openaiwebthread.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		return &ValidationError{Name: "requested_model", err: errors.New(`ent: missing required field "OpenAIWebThread.requested_model"`)}
	}
	if v, ok := _c.mutation.RequestedModel(); ok {
		if err := openaiwebthread.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.requested_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CapabilityMode(); !ok {
		return &ValidationError{Name: "capability_mode", err: errors.New(`ent: missing required field "OpenAIWebThread.capability_mode"`)}
	}
	if v, ok := _c.mutation.CapabilityMode(); ok {
		if err := openaiwebthread.CapabilityModeValidator(v); err != nil {
			return &ValidationError{Name: "capability_mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.capability_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HistoryMode(); !ok {
		return &ValidationError{Name: "history_mode", err: errors.New(`ent: missing required field "OpenAIWebThread.history_mode"`)}
	}
	if v, ok := _c.mutation.HistoryMode(); ok {
		if err := openaiwebthread.HistoryModeValidator(v); err != nil {
			return &ValidationError{Name: "history_mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.history_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CachePolicy(); !ok {
		return &ValidationError{Name: "cache_policy", err: errors.New(`ent: missing required field "OpenAIWebThread.cache_policy"`)}
	}
	if v, ok := _c.mutation.CachePolicy(); ok {
		if err := openaiwebthread.CachePolicyValidator(v); err != nil {
			return &ValidationError{Name: "cache_policy", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.cache_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncStatus(); !ok {
		return &ValidationError{Name: "sync_status", err: errors.New(`ent: missing required field "OpenAIWebThread.sync_status"`)}
	}
	if v, ok := _c.mutation.SyncStatus(); ok {
		if err := openaiwebthread.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.sync_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OpenAIWebThread.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := openaiwebthread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "OpenAIWebThread.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIWebThread.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIWebThread.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OpenAIWebThread.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "OpenAIWebThread.group"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "OpenAIWebThread.account"`)}
	}
	return nil
}

func (_c *OpenAIWebThreadCreate) sqlSave(ctx context.Context) (*OpenAIWebThread, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIWebThreadCreate) createSpec() (*OpenAIWebThread, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIWebThread{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaiwebthread.Table, sqlgraph.NewFieldSpec(openaiwebthread.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.LocalThreadID(); ok {
		_spec.SetField(openaiwebthread.FieldLocalThreadID, field.TypeString, value)
		_node.LocalThreadID = value
	}
	if value, ok := _c.mutation.PageSessionID(); ok {
		_spec.SetField(openaiwebthread.FieldPageSessionID, field.TypeString, value)
		_node.PageSessionID = value
	}
	if value, ok := _c.mutation.UpstreamConversationID(); ok {
		_spec.SetField(openaiwebthread.FieldUpstreamConversationID, field.TypeString, value)
		_node.UpstreamConversationID = &value
	}
	if value, ok := _c.mutation.UpstreamSessionID(); ok {
		_spec.SetField(openaiwebthread.FieldUpstreamSessionID, field.TypeString, value)
		_node.UpstreamSessionID = &value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(openaiwebthread.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(openaiwebthread.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(openaiwebthread.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = value
	}
	if value, ok := _c.mutation.CapabilityMode(); ok {
		_spec.SetField(openaiwebthread.FieldCapabilityMode, field.TypeString, value)
		_node.CapabilityMode = value
	}
	if value, ok := _c.mutation.HistoryMode(); ok {
		_spec.SetField(openaiwebthread.FieldHistoryMode, field.TypeString, value)
		_node.HistoryMode = value
	}
	if value, ok := _c.mutation.CachePolicy(); ok {
		_spec.SetField(openaiwebthread.FieldCachePolicy, field.TypeString, value)
		_node.CachePolicy = value
	}
	if value, ok := _c.mutation.SyncStatus(); ok {
		_spec.SetField(openaiwebthread.FieldSyncStatus, field.TypeString, value)
		_node.SyncStatus = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(openaiwebthread.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(openaiwebthread.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(openaiwebthread.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaiwebthread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiwebthread.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(openaiwebthread.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.UserTable,
			Columns: []string{openaiwebthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.GroupTable,
			Columns: []string{openaiwebthread.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.AccountTable,
			Columns: []string{openaiwebthread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIWebThread.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIWebThreadUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIWebThreadCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIWebThreadUpsertOne {
	_c.conflict = opts
	return &OpenAIWebThreadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIWebThread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIWebThreadCreate) OnConflictColumns(columns ...string) *OpenAIWebThreadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIWebThreadUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIWebThreadUpsertOne is the builder for "upsert"-ing
	//  one OpenAIWebThread node.
	OpenAIWebThreadUpsertOne struct {
		create *OpenAIWebThreadCreate
	}

	// OpenAIWebThreadUpsert is the "OnConflict" setter.
	OpenAIWebThreadUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *OpenAIWebThreadUpsert) SetUserID(v int64) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateUserID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OpenAIWebThreadUpsert) SetGroupID(v int64) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateGroupID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIWebThreadUpsert) SetAccountID(v int64) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateAccountID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldAccountID)
	return u
}

// SetLocalThreadID sets the "local_thread_id" field.
func (u *OpenAIWebThreadUpsert) SetLocalThreadID(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldLocalThreadID, v)
	return u
}

// UpdateLocalThreadID sets the "local_thread_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateLocalThreadID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldLocalThreadID)
	return u
}

// SetPageSessionID sets the "page_session_id" field.
func (u *OpenAIWebThreadUpsert) SetPageSessionID(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldPageSessionID, v)
	return u
}

// UpdatePageSessionID sets the "page_session_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdatePageSessionID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldPageSessionID)
	return u
}

// SetUpstreamConversationID sets the "upstream_conversation_id" field.
func (u *OpenAIWebThreadUpsert) SetUpstreamConversationID(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldUpstreamConversationID, v)
	return u
}

// UpdateUpstreamConversationID sets the "upstream_conversation_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateUpstreamConversationID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldUpstreamConversationID)
	return u
}

// ClearUpstreamConversationID clears the value of the "upstream_conversation_id" field.
func (u *OpenAIWebThreadUpsert) ClearUpstreamConversationID() *OpenAIWebThreadUpsert {
	u.SetNull(openaiwebthread.FieldUpstreamConversationID)
	return u
}

// SetUpstreamSessionID sets the "upstream_session_id" field.
func (u *OpenAIWebThreadUpsert) SetUpstreamSessionID(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldUpstreamSessionID, v)
	return u
}

// UpdateUpstreamSessionID sets the "upstream_session_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateUpstreamSessionID() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldUpstreamSessionID)
	return u
}

// ClearUpstreamSessionID clears the value of the "upstream_session_id" field.
func (u *OpenAIWebThreadUpsert) ClearUpstreamSessionID() *OpenAIWebThreadUpsert {
	u.SetNull(openaiwebthread.FieldUpstreamSessionID)
	return u
}

// SetProvider sets the "provider" field.
func (u *OpenAIWebThreadUpsert) SetProvider(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateProvider() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldProvider)
	return u
}

// SetTitle sets the "title" field.
func (u *OpenAIWebThreadUpsert) SetTitle(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateTitle() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldTitle)
	return u
}

// SetRequestedModel sets the "requested_model" field.
func (u *OpenAIWebThreadUpsert) SetRequestedModel(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldRequestedModel, v)
	return u
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateRequestedModel() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldRequestedModel)
	return u
}

// SetCapabilityMode sets the "capability_mode" field.
func (u *OpenAIWebThreadUpsert) SetCapabilityMode(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldCapabilityMode, v)
	return u
}

// UpdateCapabilityMode sets the "capability_mode" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateCapabilityMode() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldCapabilityMode)
	return u
}

// SetHistoryMode sets the "history_mode" field.
func (u *OpenAIWebThreadUpsert) SetHistoryMode(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldHistoryMode, v)
	return u
}

// UpdateHistoryMode sets the "history_mode" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateHistoryMode() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldHistoryMode)
	return u
}

// SetCachePolicy sets the "cache_policy" field.
func (u *OpenAIWebThreadUpsert) SetCachePolicy(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldCachePolicy, v)
	return u
}

// UpdateCachePolicy sets the "cache_policy" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateCachePolicy() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldCachePolicy)
	return u
}

// SetSyncStatus sets the "sync_status" field.
func (u *OpenAIWebThreadUpsert) SetSyncStatus(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldSyncStatus, v)
	return u
}

// UpdateSyncStatus sets the "sync_status" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateSyncStatus() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldSyncStatus)
	return u
}

// SetStatus sets the "status" field.
func (u *OpenAIWebThreadUpsert) SetStatus(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateStatus() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldStatus)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *OpenAIWebThreadUpsert) SetLastSyncedAt(v time.Time) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateLastSyncedAt() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldLastSyncedAt)
	return u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *OpenAIWebThreadUpsert) ClearLastSyncedAt() *OpenAIWebThreadUpsert {
	u.SetNull(openaiwebthread.FieldLastSyncedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *OpenAIWebThreadUpsert) SetLastError(v string) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateLastError() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldLastError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIWebThreadUpsert) SetUpdatedAt(v time.Time) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateUpdatedAt() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OpenAIWebThreadUpsert) SetDeletedAt(v time.Time) *OpenAIWebThreadUpsert {
	u.Set(openaiwebthread.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsert) UpdateDeletedAt() *OpenAIWebThreadUpsert {
	u.SetExcluded(openaiwebthread.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OpenAIWebThreadUpsert) ClearDeletedAt() *OpenAIWebThreadUpsert {
	u.SetNull(openaiwebthread.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIWebThread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIWebThreadUpsertOne) UpdateNewValues() *OpenAIWebThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaiwebthread.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIWebThread.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIWebThreadUpsertOne) Ignore() *OpenAIWebThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIWebThreadUpsertOne) DoNothing() *OpenAIWebThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIWebThreadCreate.OnConflict
// documentation for more info.
func (u *OpenAIWebThreadUpsertOne) Update(set func(*OpenAIWebThreadUpsert)) *OpenAIWebThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIWebThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *OpenAIWebThreadUpsertOne) SetUserID(v int64) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateUserID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OpenAIWebThreadUpsertOne) SetGroupID(v int64) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateGroupID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIWebThreadUpsertOne) SetAccountID(v int64) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateAccountID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateAccountID()
	})
}

// SetLocalThreadID sets the "local_thread_id" field.
func (u *OpenAIWebThreadUpsertOne) SetLocalThreadID(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetLocalThreadID(v)
	})
}

// UpdateLocalThreadID sets the "local_thread_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateLocalThreadID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateLocalThreadID()
	})
}

// SetPageSessionID sets the "page_session_id" field.
func (u *OpenAIWebThreadUpsertOne) SetPageSessionID(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetPageSessionID(v)
	})
}

// UpdatePageSessionID sets the "page_session_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdatePageSessionID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdatePageSessionID()
	})
}

// SetUpstreamConversationID sets the "upstream_conversation_id" field.
func (u *OpenAIWebThreadUpsertOne) SetUpstreamConversationID(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUpstreamConversationID(v)
	})
}

// UpdateUpstreamConversationID sets the "upstream_conversation_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateUpstreamConversationID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUpstreamConversationID()
	})
}

// ClearUpstreamConversationID clears the value of the "upstream_conversation_id" field.
func (u *OpenAIWebThreadUpsertOne) ClearUpstreamConversationID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearUpstreamConversationID()
	})
}

// SetUpstreamSessionID sets the "upstream_session_id" field.
func (u *OpenAIWebThreadUpsertOne) SetUpstreamSessionID(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUpstreamSessionID(v)
	})
}

// UpdateUpstreamSessionID sets the "upstream_session_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateUpstreamSessionID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUpstreamSessionID()
	})
}

// ClearUpstreamSessionID clears the value of the "upstream_session_id" field.
func (u *OpenAIWebThreadUpsertOne) ClearUpstreamSessionID() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearUpstreamSessionID()
	})
}

// SetProvider sets the "provider" field.
func (u *OpenAIWebThreadUpsertOne) SetProvider(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateProvider() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateProvider()
	})
}

// SetTitle sets the "title" field.
func (u *OpenAIWebThreadUpsertOne) SetTitle(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateTitle() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateTitle()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *OpenAIWebThreadUpsertOne) SetRequestedModel(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateRequestedModel() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetCapabilityMode sets the "capability_mode" field.
func (u *OpenAIWebThreadUpsertOne) SetCapabilityMode(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetCapabilityMode(v)
	})
}

// UpdateCapabilityMode sets the "capability_mode" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateCapabilityMode() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateCapabilityMode()
	})
}

// SetHistoryMode sets the "history_mode" field.
func (u *OpenAIWebThreadUpsertOne) SetHistoryMode(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetHistoryMode(v)
	})
}

// UpdateHistoryMode sets the "history_mode" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateHistoryMode() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateHistoryMode()
	})
}

// SetCachePolicy sets the "cache_policy" field.
func (u *OpenAIWebThreadUpsertOne) SetCachePolicy(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetCachePolicy(v)
	})
}

// UpdateCachePolicy sets the "cache_policy" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateCachePolicy() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateCachePolicy()
	})
}

// SetSyncStatus sets the "sync_status" field.
func (u *OpenAIWebThreadUpsertOne) SetSyncStatus(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetSyncStatus(v)
	})
}

// UpdateSyncStatus sets the "sync_status" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateSyncStatus() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateSyncStatus()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAIWebThreadUpsertOne) SetStatus(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateStatus() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *OpenAIWebThreadUpsertOne) SetLastSyncedAt(v time.Time) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateLastSyncedAt() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *OpenAIWebThreadUpsertOne) ClearLastSyncedAt() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *OpenAIWebThreadUpsertOne) SetLastError(v string) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateLastError() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIWebThreadUpsertOne) SetUpdatedAt(v time.Time) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateUpdatedAt() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OpenAIWebThreadUpsertOne) SetDeletedAt(v time.Time) *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertOne) UpdateDeletedAt() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OpenAIWebThreadUpsertOne) ClearDeletedAt() *OpenAIWebThreadUpsertOne {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *OpenAIWebThreadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIWebThreadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIWebThreadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIWebThreadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIWebThreadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIWebThreadCreateBulk is the builder for creating many OpenAIWebThread entities in bulk.
type OpenAIWebThreadCreateBulk struct {
	config
	err      error
	builders []*OpenAIWebThreadCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIWebThread entities in the database.
func (_c *OpenAIWebThreadCreateBulk) Save(ctx context.Context) ([]*OpenAIWebThread, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIWebThread, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIWebThreadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIWebThreadCreateBulk) SaveX(ctx context.Context) []*OpenAIWebThread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIWebThreadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIWebThreadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIWebThread.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIWebThreadUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIWebThreadCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIWebThreadUpsertBulk {
	_c.conflict = opts
	return &OpenAIWebThreadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIWebThread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIWebThreadCreateBulk) OnConflictColumns(columns ...string) *OpenAIWebThreadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIWebThreadUpsertBulk{
		create: _c,
	}
}

// OpenAIWebThreadUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIWebThread nodes.
type OpenAIWebThreadUpsertBulk struct {
	create *OpenAIWebThreadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIWebThread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIWebThreadUpsertBulk) UpdateNewValues() *OpenAIWebThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaiwebthread.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIWebThread.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIWebThreadUpsertBulk) Ignore() *OpenAIWebThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIWebThreadUpsertBulk) DoNothing() *OpenAIWebThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIWebThreadCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIWebThreadUpsertBulk) Update(set func(*OpenAIWebThreadUpsert)) *OpenAIWebThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIWebThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetUserID(v int64) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateUserID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetGroupID(v int64) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateGroupID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetAccountID(v int64) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateAccountID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateAccountID()
	})
}

// SetLocalThreadID sets the "local_thread_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetLocalThreadID(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetLocalThreadID(v)
	})
}

// UpdateLocalThreadID sets the "local_thread_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateLocalThreadID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateLocalThreadID()
	})
}

// SetPageSessionID sets the "page_session_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetPageSessionID(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetPageSessionID(v)
	})
}

// UpdatePageSessionID sets the "page_session_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdatePageSessionID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdatePageSessionID()
	})
}

// SetUpstreamConversationID sets the "upstream_conversation_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetUpstreamConversationID(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUpstreamConversationID(v)
	})
}

// UpdateUpstreamConversationID sets the "upstream_conversation_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateUpstreamConversationID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUpstreamConversationID()
	})
}

// ClearUpstreamConversationID clears the value of the "upstream_conversation_id" field.
func (u *OpenAIWebThreadUpsertBulk) ClearUpstreamConversationID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearUpstreamConversationID()
	})
}

// SetUpstreamSessionID sets the "upstream_session_id" field.
func (u *OpenAIWebThreadUpsertBulk) SetUpstreamSessionID(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUpstreamSessionID(v)
	})
}

// UpdateUpstreamSessionID sets the "upstream_session_id" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateUpstreamSessionID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUpstreamSessionID()
	})
}

// ClearUpstreamSessionID clears the value of the "upstream_session_id" field.
func (u *OpenAIWebThreadUpsertBulk) ClearUpstreamSessionID() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearUpstreamSessionID()
	})
}

// SetProvider sets the "provider" field.
func (u *OpenAIWebThreadUpsertBulk) SetProvider(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateProvider() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateProvider()
	})
}

// SetTitle sets the "title" field.
func (u *OpenAIWebThreadUpsertBulk) SetTitle(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateTitle() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateTitle()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *OpenAIWebThreadUpsertBulk) SetRequestedModel(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateRequestedModel() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetCapabilityMode sets the "capability_mode" field.
func (u *OpenAIWebThreadUpsertBulk) SetCapabilityMode(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetCapabilityMode(v)
	})
}

// UpdateCapabilityMode sets the "capability_mode" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateCapabilityMode() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateCapabilityMode()
	})
}

// SetHistoryMode sets the "history_mode" field.
func (u *OpenAIWebThreadUpsertBulk) SetHistoryMode(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetHistoryMode(v)
	})
}

// UpdateHistoryMode sets the "history_mode" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateHistoryMode() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateHistoryMode()
	})
}

// SetCachePolicy sets the "cache_policy" field.
func (u *OpenAIWebThreadUpsertBulk) SetCachePolicy(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetCachePolicy(v)
	})
}

// UpdateCachePolicy sets the "cache_policy" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateCachePolicy() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateCachePolicy()
	})
}

// SetSyncStatus sets the "sync_status" field.
func (u *OpenAIWebThreadUpsertBulk) SetSyncStatus(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetSyncStatus(v)
	})
}

// UpdateSyncStatus sets the "sync_status" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateSyncStatus() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateSyncStatus()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAIWebThreadUpsertBulk) SetStatus(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateStatus() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *OpenAIWebThreadUpsertBulk) SetLastSyncedAt(v time.Time) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateLastSyncedAt() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *OpenAIWebThreadUpsertBulk) ClearLastSyncedAt() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *OpenAIWebThreadUpsertBulk) SetLastError(v string) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateLastError() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIWebThreadUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateUpdatedAt() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OpenAIWebThreadUpsertBulk) SetDeletedAt(v time.Time) *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OpenAIWebThreadUpsertBulk) UpdateDeletedAt() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OpenAIWebThreadUpsertBulk) ClearDeletedAt() *OpenAIWebThreadUpsertBulk {
	return u.Update(func(s *OpenAIWebThreadUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *OpenAIWebThreadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIWebThreadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIWebThreadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIWebThreadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
