// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/openaiwebthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OpenAIWebThread is the model entity for the OpenAIWebThread schema.
type OpenAIWebThread struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// LocalThreadID holds the value of the "local_thread_id" field.
	LocalThreadID string `json:"local_thread_id,omitempty"`
	// PageSessionID holds the value of the "page_session_id" field.
	PageSessionID string `json:"page_session_id,omitempty"`
	// UpstreamConversationID holds the value of the "upstream_conversation_id" field.
	UpstreamConversationID *string `json:"upstream_conversation_id,omitempty"`
	// UpstreamSessionID holds the value of the "upstream_session_id" field.
	UpstreamSessionID *string `json:"upstream_session_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// CapabilityMode holds the value of the "capability_mode" field.
	CapabilityMode string `json:"capability_mode,omitempty"`
	// HistoryMode holds the value of the "history_mode" field.
	HistoryMode string `json:"history_mode,omitempty"`
	// CachePolicy holds the value of the "cache_policy" field.
	CachePolicy string `json:"cache_policy,omitempty"`
	// SyncStatus holds the value of the "sync_status" field.
	SyncStatus string `json:"sync_status,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OpenAIWebThreadQuery when eager-loading is set.
	Edges        OpenAIWebThreadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OpenAIWebThreadEdges holds the relations/edges for other nodes in the graph.
type OpenAIWebThreadEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OpenAIWebThreadEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OpenAIWebThreadEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OpenAIWebThreadEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIWebThread) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaiwebthread.FieldID, openaiwebthread.FieldUserID, openaiwebthread.FieldGroupID, openaiwebthread.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case openaiwebthread.FieldLocalThreadID, openaiwebthread.FieldPageSessionID, openaiwebthread.FieldUpstreamConversationID, openaiwebthread.FieldUpstreamSessionID, openaiwebthread.FieldProvider, openaiwebthread.FieldTitle, openaiwebthread.FieldRequestedModel, openaiwebthread.FieldCapabilityMode, openaiwebthread.FieldHistoryMode, openaiwebthread.FieldCachePolicy, openaiwebthread.FieldSyncStatus, openaiwebthread.FieldStatus, openaiwebthread.FieldLastError:
			values[i] = new(sql.NullString)
		case openaiwebthread.FieldLastSyncedAt, openaiwebthread.FieldCreatedAt, openaiwebthread.FieldUpdatedAt, openaiwebthread.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIWebThread fields.
func (_m *OpenAIWebThread) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaiwebthread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaiwebthread.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case openaiwebthread.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case openaiwebthread.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaiwebthread.FieldLocalThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_thread_id", values[i])
			} else if value.Valid {
				_m.LocalThreadID = value.String
			}
		case openaiwebthread.FieldPageSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field page_session_id", values[i])
			} else if value.Valid {
				_m.PageSessionID = value.String
			}
		case openaiwebthread.FieldUpstreamConversationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_conversation_id", values[i])
			} else if value.Valid {
				_m.UpstreamConversationID = new(string)
				*_m.UpstreamConversationID = value.String
			}
		case openaiwebthread.FieldUpstreamSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_session_id", values[i])
			} else if value.Valid {
				_m.UpstreamSessionID = new(string)
				*_m.UpstreamSessionID = value.String
			}
		case openaiwebthread.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case openaiwebthread.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case openaiwebthread.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case openaiwebthread.FieldCapabilityMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capability_mode", values[i])
			} else if value.Valid {
				_m.CapabilityMode = value.String
			}
		case openaiwebthread.FieldHistoryMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field history_mode", values[i])
			} else if value.Valid {
				_m.HistoryMode = value.String
			}
		case openaiwebthread.FieldCachePolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cache_policy", values[i])
			} else if value.Valid {
				_m.CachePolicy = value.String
			}
		case openaiwebthread.FieldSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_status", values[i])
			} else if value.Valid {
				_m.SyncStatus = value.String
			}
		case openaiwebthread.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case openaiwebthread.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case openaiwebthread.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case openaiwebthread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaiwebthread.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case openaiwebthread.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIWebThread.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIWebThread) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OpenAIWebThread entity.
func (_m *OpenAIWebThread) QueryUser() *UserQuery {
	return NewOpenAIWebThreadClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the OpenAIWebThread entity.
func (_m *OpenAIWebThread) QueryGroup() *GroupQuery {
	return NewOpenAIWebThreadClient(_m.config).QueryGroup(_m)
}

// QueryAccount queries the "account" edge of the OpenAIWebThread entity.
func (_m *OpenAIWebThread) QueryAccount() *AccountQuery {
	return NewOpenAIWebThreadClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this OpenAIWebThread.
// Note that you need to call OpenAIWebThread.Unwrap() before calling this method if this OpenAIWebThread
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIWebThread) Update() *OpenAIWebThreadUpdateOne {
	return NewOpenAIWebThreadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIWebThread entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIWebThread) Unwrap() *OpenAIWebThread {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIWebThread is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIWebThread) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIWebThread(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("local_thread_id=")
	builder.WriteString(_m.LocalThreadID)
	builder.WriteString(", ")
	builder.WriteString("page_session_id=")
	builder.WriteString(_m.PageSessionID)
	builder.WriteString(", ")
	if v := _m.UpstreamConversationID; v != nil {
		builder.WriteString("upstream_conversation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamSessionID; v != nil {
		builder.WriteString("upstream_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("capability_mode=")
	builder.WriteString(_m.CapabilityMode)
	builder.WriteString(", ")
	builder.WriteString("history_mode=")
	builder.WriteString(_m.HistoryMode)
	builder.WriteString(", ")
	builder.WriteString("cache_policy=")
	builder.WriteString(_m.CachePolicy)
	builder.WriteString(", ")
	builder.WriteString("sync_status=")
	builder.WriteString(_m.SyncStatus)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIWebThreads is a parsable slice of OpenAIWebThread.
type OpenAIWebThreads []*OpenAIWebThread
