// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/openaiwebthread"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OpenAIWebThreadUpdate is the builder for updating OpenAIWebThread entities.
type OpenAIWebThreadUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIWebThreadMutation
}

// Where appends a list predicates to the OpenAIWebThreadUpdate builder.
func (_u *OpenAIWebThreadUpdate) Where(ps ...predicate.OpenAIWebThread) *OpenAIWebThreadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OpenAIWebThreadUpdate) SetUserID(v int64) *OpenAIWebThreadUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableUserID(v *int64) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OpenAIWebThreadUpdate) SetGroupID(v int64) *OpenAIWebThreadUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableGroupID(v *int64) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIWebThreadUpdate) SetAccountID(v int64) *OpenAIWebThreadUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableAccountID(v *int64) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetLocalThreadID sets the "local_thread_id" field.
func (_u *OpenAIWebThreadUpdate) SetLocalThreadID(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetLocalThreadID(v)
	return _u
}

// SetNillableLocalThreadID sets the "local_thread_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableLocalThreadID(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetLocalThreadID(*v)
	}
	return _u
}

// SetPageSessionID sets the "page_session_id" field.
func (_u *OpenAIWebThreadUpdate) SetPageSessionID(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetPageSessionID(v)
	return _u
}

// SetNillablePageSessionID sets the "page_session_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillablePageSessionID(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetPageSessionID(*v)
	}
	return _u
}

// SetUpstreamConversationID sets the "upstream_conversation_id" field.
func (_u *OpenAIWebThreadUpdate) SetUpstreamConversationID(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetUpstreamConversationID(v)
	return _u
}

// SetNillableUpstreamConversationID sets the "upstream_conversation_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableUpstreamConversationID(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetUpstreamConversationID(*v)
	}
	return _u
}

// ClearUpstreamConversationID clears the value of the "upstream_conversation_id" field.
func (_u *OpenAIWebThreadUpdate) ClearUpstreamConversationID() *OpenAIWebThreadUpdate {
	_u.mutation.ClearUpstreamConversationID()
	return _u
}

// SetUpstreamSessionID sets the "upstream_session_id" field.
func (_u *OpenAIWebThreadUpdate) SetUpstreamSessionID(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetUpstreamSessionID(v)
	return _u
}

// SetNillableUpstreamSessionID sets the "upstream_session_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableUpstreamSessionID(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetUpstreamSessionID(*v)
	}
	return _u
}

// ClearUpstreamSessionID clears the value of the "upstream_session_id" field.
func (_u *OpenAIWebThreadUpdate) ClearUpstreamSessionID() *OpenAIWebThreadUpdate {
	_u.mutation.ClearUpstreamSessionID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OpenAIWebThreadUpdate) SetProvider(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableProvider(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *OpenAIWebThreadUpdate) SetTitle(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableTitle(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *OpenAIWebThreadUpdate) SetRequestedModel(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableRequestedModel(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetCapabilityMode sets the "capability_mode" field.
func (_u *OpenAIWebThreadUpdate) SetCapabilityMode(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetCapabilityMode(v)
	return _u
}

// SetNillableCapabilityMode sets the "capability_mode" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableCapabilityMode(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetCapabilityMode(*v)
	}
	return _u
}

// SetHistoryMode sets the "history_mode" field.
func (_u *OpenAIWebThreadUpdate) SetHistoryMode(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetHistoryMode(v)
	return _u
}

// SetNillableHistoryMode sets the "history_mode" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableHistoryMode(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetHistoryMode(*v)
	}
	return _u
}

// SetCachePolicy sets the "cache_policy" field.
func (_u *OpenAIWebThreadUpdate) SetCachePolicy(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetCachePolicy(v)
	return _u
}

// SetNillableCachePolicy sets the "cache_policy" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableCachePolicy(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetCachePolicy(*v)
	}
	return _u
}

// SetSyncStatus sets the "sync_status" field.
func (_u *OpenAIWebThreadUpdate) SetSyncStatus(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetSyncStatus(v)
	return _u
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableSyncStatus(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetSyncStatus(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAIWebThreadUpdate) SetStatus(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableStatus(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *OpenAIWebThreadUpdate) SetLastSyncedAt(v time.Time) *OpenAIWebThreadUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableLastSyncedAt(v *time.Time) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *OpenAIWebThreadUpdate) ClearLastSyncedAt() *OpenAIWebThreadUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OpenAIWebThreadUpdate) SetLastError(v string) *OpenAIWebThreadUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableLastError(v *string) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIWebThreadUpdate) SetUpdatedAt(v time.Time) *OpenAIWebThreadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OpenAIWebThreadUpdate) SetDeletedAt(v time.Time) *OpenAIWebThreadUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdate) SetNillableDeletedAt(v *time.Time) *OpenAIWebThreadUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OpenAIWebThreadUpdate) ClearDeletedAt() *OpenAIWebThreadUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OpenAIWebThreadUpdate) SetUser(v *User) *OpenAIWebThreadUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OpenAIWebThreadUpdate) SetGroup(v *Group) *OpenAIWebThreadUpdate {
	return _u.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OpenAIWebThreadUpdate) SetAccount(v *Account) *OpenAIWebThreadUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the OpenAIWebThreadMutation object of the builder.
func (_u *OpenAIWebThreadUpdate) Mutation() *OpenAIWebThreadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OpenAIWebThreadUpdate) ClearUser() *OpenAIWebThreadUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OpenAIWebThreadUpdate) ClearGroup() *OpenAIWebThreadUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OpenAIWebThreadUpdate) ClearAccount() *OpenAIWebThreadUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIWebThreadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIWebThreadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIWebThreadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIWebThreadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIWebThreadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaiwebthread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIWebThreadUpdate) check() error {
	if v, ok := _u.mutation.LocalThreadID(); ok {
		if err := openaiwebthread.LocalThreadIDValidator(v); err != nil {
			return &ValidationError{Name: "local_thread_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.local_thread_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageSessionID(); ok {
		if err := openaiwebthread.PageSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "page_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.page_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamConversationID(); ok {
		if err := openaiwebthread.UpstreamConversationIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_conversation_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.upstream_conversation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamSessionID(); ok {
		if err := openaiwebthread.UpstreamSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.upstream_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := openaiwebthread.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := openaiwebthread.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := openaiwebthread.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CapabilityMode(); ok {
		if err := openaiwebthread.CapabilityModeValidator(v); err != nil {
			return &ValidationError{Name: "capability_mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.capability_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HistoryMode(); ok {
		if err := openaiwebthread.HistoryModeValidator(v); err != nil {
			return &ValidationError{Name: "history_mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.history_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CachePolicy(); ok {
		if err := openaiwebthread.CachePolicyValidator(v); err != nil {
			return &ValidationError{Name: "cache_policy", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.cache_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncStatus(); ok {
		if err := openaiwebthread.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.sync_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openaiwebthread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIWebThread.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIWebThread.group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIWebThread.account"`)
	}
	return nil
}

func (_u *OpenAIWebThreadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaiwebthread.Table, openaiwebthread.Columns, sqlgraph.NewFieldSpec(openaiwebthread.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LocalThreadID(); ok {
		_spec.SetField(openaiwebthread.FieldLocalThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageSessionID(); ok {
		_spec.SetField(openaiwebthread.FieldPageSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamConversationID(); ok {
		_spec.SetField(openaiwebthread.FieldUpstreamConversationID, field.TypeString, value)
	}
	if _u.mutation.UpstreamConversationIDCleared() {
		_spec.ClearField(openaiwebthread.FieldUpstreamConversationID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamSessionID(); ok {
		_spec.SetField(openaiwebthread.FieldUpstreamSessionID, field.TypeString, value)
	}
	if _u.mutation.UpstreamSessionIDCleared() {
		_spec.ClearField(openaiwebthread.FieldUpstreamSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(openaiwebthread.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(openaiwebthread.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(openaiwebthread.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.CapabilityMode(); ok {
		_spec.SetField(openaiwebthread.FieldCapabilityMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.HistoryMode(); ok {
		_spec.SetField(openaiwebthread.FieldHistoryMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CachePolicy(); ok {
		_spec.SetField(openaiwebthread.FieldCachePolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncStatus(); ok {
		_spec.SetField(openaiwebthread.FieldSyncStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openaiwebthread.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(openaiwebthread.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(openaiwebthread.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(openaiwebthread.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiwebthread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(openaiwebthread.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(openaiwebthread.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.UserTable,
			Columns: []string{openaiwebthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.UserTable,
			Columns: []string{openaiwebthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.GroupTable,
			Columns: []string{openaiwebthread.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.GroupTable,
			Columns: []string{openaiwebthread.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.AccountTable,
			Columns: []string{openaiwebthread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.AccountTable,
			Columns: []string{openaiwebthread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiwebthread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIWebThreadUpdateOne is the builder for updating a single OpenAIWebThread entity.
type OpenAIWebThreadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIWebThreadMutation
}

// SetUserID sets the "user_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetUserID(v int64) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableUserID(v *int64) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetGroupID(v int64) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableGroupID(v *int64) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetAccountID(v int64) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableAccountID(v *int64) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetLocalThreadID sets the "local_thread_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetLocalThreadID(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetLocalThreadID(v)
	return _u
}

// SetNillableLocalThreadID sets the "local_thread_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableLocalThreadID(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetLocalThreadID(*v)
	}
	return _u
}

// SetPageSessionID sets the "page_session_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetPageSessionID(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetPageSessionID(v)
	return _u
}

// SetNillablePageSessionID sets the "page_session_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillablePageSessionID(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetPageSessionID(*v)
	}
	return _u
}

// SetUpstreamConversationID sets the "upstream_conversation_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetUpstreamConversationID(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetUpstreamConversationID(v)
	return _u
}

// SetNillableUpstreamConversationID sets the "upstream_conversation_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableUpstreamConversationID(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetUpstreamConversationID(*v)
	}
	return _u
}

// ClearUpstreamConversationID clears the value of the "upstream_conversation_id" field.
func (_u *OpenAIWebThreadUpdateOne) ClearUpstreamConversationID() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearUpstreamConversationID()
	return _u
}

// SetUpstreamSessionID sets the "upstream_session_id" field.
func (_u *OpenAIWebThreadUpdateOne) SetUpstreamSessionID(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetUpstreamSessionID(v)
	return _u
}

// SetNillableUpstreamSessionID sets the "upstream_session_id" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableUpstreamSessionID(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetUpstreamSessionID(*v)
	}
	return _u
}

// ClearUpstreamSessionID clears the value of the "upstream_session_id" field.
func (_u *OpenAIWebThreadUpdateOne) ClearUpstreamSessionID() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearUpstreamSessionID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OpenAIWebThreadUpdateOne) SetProvider(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableProvider(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *OpenAIWebThreadUpdateOne) SetTitle(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableTitle(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *OpenAIWebThreadUpdateOne) SetRequestedModel(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableRequestedModel(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetCapabilityMode sets the "capability_mode" field.
func (_u *OpenAIWebThreadUpdateOne) SetCapabilityMode(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetCapabilityMode(v)
	return _u
}

// SetNillableCapabilityMode sets the "capability_mode" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableCapabilityMode(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetCapabilityMode(*v)
	}
	return _u
}

// SetHistoryMode sets the "history_mode" field.
func (_u *OpenAIWebThreadUpdateOne) SetHistoryMode(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetHistoryMode(v)
	return _u
}

// SetNillableHistoryMode sets the "history_mode" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableHistoryMode(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetHistoryMode(*v)
	}
	return _u
}

// SetCachePolicy sets the "cache_policy" field.
func (_u *OpenAIWebThreadUpdateOne) SetCachePolicy(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetCachePolicy(v)
	return _u
}

// SetNillableCachePolicy sets the "cache_policy" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableCachePolicy(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetCachePolicy(*v)
	}
	return _u
}

// SetSyncStatus sets the "sync_status" field.
func (_u *OpenAIWebThreadUpdateOne) SetSyncStatus(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetSyncStatus(v)
	return _u
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableSyncStatus(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetSyncStatus(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAIWebThreadUpdateOne) SetStatus(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableStatus(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *OpenAIWebThreadUpdateOne) SetLastSyncedAt(v time.Time) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableLastSyncedAt(v *time.Time) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *OpenAIWebThreadUpdateOne) ClearLastSyncedAt() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OpenAIWebThreadUpdateOne) SetLastError(v string) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableLastError(v *string) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIWebThreadUpdateOne) SetUpdatedAt(v time.Time) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OpenAIWebThreadUpdateOne) SetDeletedAt(v time.Time) *OpenAIWebThreadUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OpenAIWebThreadUpdateOne) SetNillableDeletedAt(v *time.Time) *OpenAIWebThreadUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OpenAIWebThreadUpdateOne) ClearDeletedAt() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OpenAIWebThreadUpdateOne) SetUser(v *User) *OpenAIWebThreadUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OpenAIWebThreadUpdateOne) SetGroup(v *Group) *OpenAIWebThreadUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OpenAIWebThreadUpdateOne) SetAccount(v *Account) *OpenAIWebThreadUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the OpenAIWebThreadMutation object of the builder.
func (_u *OpenAIWebThreadUpdateOne) Mutation() *OpenAIWebThreadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OpenAIWebThreadUpdateOne) ClearUser() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OpenAIWebThreadUpdateOne) ClearGroup() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OpenAIWebThreadUpdateOne) ClearAccount() *OpenAIWebThreadUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the OpenAIWebThreadUpdate builder.
func (_u *OpenAIWebThreadUpdateOne) Where(ps ...predicate.OpenAIWebThread) *OpenAIWebThreadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIWebThreadUpdateOne) Select(field string, fields ...string) *OpenAIWebThreadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIWebThread entity.
func (_u *OpenAIWebThreadUpdateOne) Save(ctx context.Context) (*OpenAIWebThread, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIWebThreadUpdateOne) SaveX(ctx context.Context) *OpenAIWebThread {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIWebThreadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIWebThreadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIWebThreadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaiwebthread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIWebThreadUpdateOne) check() error {
	if v, ok := _u.mutation.LocalThreadID(); ok {
		if err := openaiwebthread.LocalThreadIDValidator(v); err != nil {
			return &ValidationError{Name: "local_thread_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.local_thread_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PageSessionID(); ok {
		if err := openaiwebthread.PageSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "page_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.page_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamConversationID(); ok {
		if err := openaiwebthread.UpstreamConversationIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_conversation_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.upstream_conversation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamSessionID(); ok {
		if err := openaiwebthread.UpstreamSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.upstream_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := openaiwebthread.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := openaiwebthread.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := openaiwebthread.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CapabilityMode(); ok {
		if err := openaiwebthread.CapabilityModeValidator(v); err != nil {
			return &ValidationError{Name: "capability_mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.capability_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HistoryMode(); ok {
		if err := openaiwebthread.HistoryModeValidator(v); err != nil {
			return &ValidationError{Name: "history_mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.history_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CachePolicy(); ok {
		if err := openaiwebthread.CachePolicyValidator(v); err != nil {
			return &ValidationError{Name: "cache_policy", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.cache_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncStatus(); ok {
		if err := openaiwebthread.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.sync_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openaiwebthread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIWebThread.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIWebThread.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIWebThread.group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIWebThread.account"`)
	}
	return nil
}

func (_u *OpenAIWebThreadUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIWebThread, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaiwebthread.Table, openaiwebthread.Columns, sqlgraph.NewFieldSpec(openaiwebthread.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIWebThread.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaiwebthread.FieldID)
		for _, f := range fields {
			if !openaiwebthread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaiwebthread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LocalThreadID(); ok {
		_spec.SetField(openaiwebthread.FieldLocalThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageSessionID(); ok {
		_spec.SetField(openaiwebthread.FieldPageSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamConversationID(); ok {
		_spec.SetField(openaiwebthread.FieldUpstreamConversationID, field.TypeString, value)
	}
	if _u.mutation.UpstreamConversationIDCleared() {
		_spec.ClearField(openaiwebthread.FieldUpstreamConversationID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamSessionID(); ok {
		_spec.SetField(openaiwebthread.FieldUpstreamSessionID, field.TypeString, value)
	}
	if _u.mutation.UpstreamSessionIDCleared() {
		_spec.ClearField(openaiwebthread.FieldUpstreamSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(openaiwebthread.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(openaiwebthread.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(openaiwebthread.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.CapabilityMode(); ok {
		_spec.SetField(openaiwebthread.FieldCapabilityMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.HistoryMode(); ok {
		_spec.SetField(openaiwebthread.FieldHistoryMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CachePolicy(); ok {
		_spec.SetField(openaiwebthread.FieldCachePolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncStatus(); ok {
		_spec.SetField(openaiwebthread.FieldSyncStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openaiwebthread.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(openaiwebthread.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(openaiwebthread.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(openaiwebthread.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiwebthread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(openaiwebthread.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(openaiwebthread.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.UserTable,
			Columns: []string{openaiwebthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.UserTable,
			Columns: []string{openaiwebthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.GroupTable,
			Columns: []string{openaiwebthread.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.GroupTable,
			Columns: []string{openaiwebthread.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.AccountTable,
			Columns: []string{openaiwebthread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaiwebthread.AccountTable,
			Columns: []string{openaiwebthread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OpenAIWebThread{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiwebthread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
