// Code generated by ent, DO NOT EDIT.

package openaiwebthread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the openaiwebthread type in the database.
	Label = "open_ai_web_thread"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldLocalThreadID holds the string denoting the local_thread_id field in the database.
	FieldLocalThreadID = "local_thread_id"
	// FieldPageSessionID holds the string denoting the page_session_id field in the database.
	FieldPageSessionID = "page_session_id"
	// FieldUpstreamConversationID holds the string denoting the upstream_conversation_id field in the database.
	FieldUpstreamConversationID = "upstream_conversation_id"
	// FieldUpstreamSessionID holds the string denoting the upstream_session_id field in the database.
	FieldUpstreamSessionID = "upstream_session_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldCapabilityMode holds the string denoting the capability_mode field in the database.
	FieldCapabilityMode = "capability_mode"
	// FieldHistoryMode holds the string denoting the history_mode field in the database.
	FieldHistoryMode = "history_mode"
	// FieldCachePolicy holds the string denoting the cache_policy field in the database.
	FieldCachePolicy = "cache_policy"
	// FieldSyncStatus holds the string denoting the sync_status field in the database.
	FieldSyncStatus = "sync_status"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the openaiwebthread in the database.
	Table = "openai_web_threads"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "openai_web_threads"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "openai_web_threads"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "openai_web_threads"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for openaiwebthread fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldGroupID,
	FieldAccountID,
	FieldLocalThreadID,
	FieldPageSessionID,
	FieldUpstreamConversationID,
	FieldUpstreamSessionID,
	FieldProvider,
	FieldTitle,
	FieldRequestedModel,
	FieldCapabilityMode,
	FieldHistoryMode,
	FieldCachePolicy,
	FieldSyncStatus,
	FieldStatus,
	FieldLastSyncedAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LocalThreadIDValidator is a validator for the "local_thread_id" field. It is called by the builders before save.
	LocalThreadIDValidator func(string) error
	// PageSessionIDValidator is a validator for the "page_session_id" field. It is called by the builders before save.
	PageSessionIDValidator func(string) error
	// UpstreamConversationIDValidator is a validator for the "upstream_conversation_id" field. It is called by the builders before save.
	UpstreamConversationIDValidator func(string) error
	// UpstreamSessionIDValidator is a validator for the "upstream_session_id" field. It is called by the builders before save.
	UpstreamSessionIDValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultRequestedModel holds the default value on creation for the "requested_model" field.
	DefaultRequestedModel string
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// DefaultCapabilityMode holds the default value on creation for the "capability_mode" field.
	DefaultCapabilityMode string
	// CapabilityModeValidator is a validator for the "capability_mode" field. It is called by the builders before save.
	CapabilityModeValidator func(string) error
	// DefaultHistoryMode holds the default value on creation for the "history_mode" field.
	DefaultHistoryMode string
	// HistoryModeValidator is a validator for the "history_mode" field. It is called by the builders before save.
	HistoryModeValidator func(string) error
	// DefaultCachePolicy holds the default value on creation for the "cache_policy" field.
	DefaultCachePolicy string
	// CachePolicyValidator is a validator for the "cache_policy" field. It is called by the builders before save.
	CachePolicyValidator func(string) error
	// DefaultSyncStatus holds the default value on creation for the "sync_status" field.
	DefaultSyncStatus string
	// SyncStatusValidator is a validator for the "sync_status" field. It is called by the builders before save.
	SyncStatusValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAIWebThread queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByLocalThreadID orders the results by the local_thread_id field.
func ByLocalThreadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalThreadID, opts...).ToFunc()
}

// ByPageSessionID orders the results by the page_session_id field.
func ByPageSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageSessionID, opts...).ToFunc()
}

// ByUpstreamConversationID orders the results by the upstream_conversation_id field.
func ByUpstreamConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamConversationID, opts...).ToFunc()
}

// ByUpstreamSessionID orders the results by the upstream_session_id field.
func ByUpstreamSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamSessionID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByCapabilityMode orders the results by the capability_mode field.
func ByCapabilityMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityMode, opts...).ToFunc()
}

// ByHistoryMode orders the results by the history_mode field.
func ByHistoryMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryMode, opts...).ToFunc()
}

// ByCachePolicy orders the results by the cache_policy field.
func ByCachePolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachePolicy, opts...).ToFunc()
}

// BySyncStatus orders the results by the sync_status field.
func BySyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncStatus, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
