// Code generated by ent, DO NOT EDIT.

package openaiwebthread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldAccountID, v))
}

// LocalThreadID applies equality check predicate on the "local_thread_id" field. It's identical to LocalThreadIDEQ.
func LocalThreadID(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldLocalThreadID, v))
}

// PageSessionID applies equality check predicate on the "page_session_id" field. It's identical to PageSessionIDEQ.
func PageSessionID(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldPageSessionID, v))
}

// UpstreamConversationID applies equality check predicate on the "upstream_conversation_id" field. It's identical to UpstreamConversationIDEQ.
func UpstreamConversationID(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUpstreamConversationID, v))
}

// UpstreamSessionID applies equality check predicate on the "upstream_session_id" field. It's identical to UpstreamSessionIDEQ.
func UpstreamSessionID(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUpstreamSessionID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldProvider, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldTitle, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldRequestedModel, v))
}

// CapabilityMode applies equality check predicate on the "capability_mode" field. It's identical to CapabilityModeEQ.
func CapabilityMode(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldCapabilityMode, v))
}

// HistoryMode applies equality check predicate on the "history_mode" field. It's identical to HistoryModeEQ.
func HistoryMode(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldHistoryMode, v))
}

// CachePolicy applies equality check predicate on the "cache_policy" field. It's identical to CachePolicyEQ.
func CachePolicy(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldCachePolicy, v))
}

// SyncStatus applies equality check predicate on the "sync_status" field. It's identical to SyncStatusEQ.
func SyncStatus(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldSyncStatus, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldStatus, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldDeletedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldGroupID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldAccountID, vs...))
}

// LocalThreadIDEQ applies the EQ predicate on the "local_thread_id" field.
func LocalThreadIDEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldLocalThreadID, v))
}

// LocalThreadIDNEQ applies the NEQ predicate on the "local_thread_id" field.
func LocalThreadIDNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldLocalThreadID, v))
}

// LocalThreadIDIn applies the In predicate on the "local_thread_id" field.
func LocalThreadIDIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldLocalThreadID, vs...))
}

// LocalThreadIDNotIn applies the NotIn predicate on the "local_thread_id" field.
func LocalThreadIDNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldLocalThreadID, vs...))
}

// LocalThreadIDGT applies the GT predicate on the "local_thread_id" field.
func LocalThreadIDGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldLocalThreadID, v))
}

// LocalThreadIDGTE applies the GTE predicate on the "local_thread_id" field.
func LocalThreadIDGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldLocalThreadID, v))
}

// LocalThreadIDLT applies the LT predicate on the "local_thread_id" field.
func LocalThreadIDLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldLocalThreadID, v))
}

// LocalThreadIDLTE applies the LTE predicate on the "local_thread_id" field.
func LocalThreadIDLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldLocalThreadID, v))
}

// LocalThreadIDContains applies the Contains predicate on the "local_thread_id" field.
func LocalThreadIDContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldLocalThreadID, v))
}

// LocalThreadIDHasPrefix applies the HasPrefix predicate on the "local_thread_id" field.
func LocalThreadIDHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldLocalThreadID, v))
}

// LocalThreadIDHasSuffix applies the HasSuffix predicate on the "local_thread_id" field.
func LocalThreadIDHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldLocalThreadID, v))
}

// LocalThreadIDEqualFold applies the EqualFold predicate on the "local_thread_id" field.
func LocalThreadIDEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldLocalThreadID, v))
}

// LocalThreadIDContainsFold applies the ContainsFold predicate on the "local_thread_id" field.
func LocalThreadIDContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldLocalThreadID, v))
}

// PageSessionIDEQ applies the EQ predicate on the "page_session_id" field.
func PageSessionIDEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldPageSessionID, v))
}

// PageSessionIDNEQ applies the NEQ predicate on the "page_session_id" field.
func PageSessionIDNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldPageSessionID, v))
}

// PageSessionIDIn applies the In predicate on the "page_session_id" field.
func PageSessionIDIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldPageSessionID, vs...))
}

// PageSessionIDNotIn applies the NotIn predicate on the "page_session_id" field.
func PageSessionIDNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldPageSessionID, vs...))
}

// PageSessionIDGT applies the GT predicate on the "page_session_id" field.
func PageSessionIDGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldPageSessionID, v))
}

// PageSessionIDGTE applies the GTE predicate on the "page_session_id" field.
func PageSessionIDGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldPageSessionID, v))
}

// PageSessionIDLT applies the LT predicate on the "page_session_id" field.
func PageSessionIDLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldPageSessionID, v))
}

// PageSessionIDLTE applies the LTE predicate on the "page_session_id" field.
func PageSessionIDLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldPageSessionID, v))
}

// PageSessionIDContains applies the Contains predicate on the "page_session_id" field.
func PageSessionIDContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldPageSessionID, v))
}

// PageSessionIDHasPrefix applies the HasPrefix predicate on the "page_session_id" field.
func PageSessionIDHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldPageSessionID, v))
}

// PageSessionIDHasSuffix applies the HasSuffix predicate on the "page_session_id" field.
func PageSessionIDHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldPageSessionID, v))
}

// PageSessionIDEqualFold applies the EqualFold predicate on the "page_session_id" field.
func PageSessionIDEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldPageSessionID, v))
}

// PageSessionIDContainsFold applies the ContainsFold predicate on the "page_session_id" field.
func PageSessionIDContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldPageSessionID, v))
}

// UpstreamConversationIDEQ applies the EQ predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDNEQ applies the NEQ predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDIn applies the In predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldUpstreamConversationID, vs...))
}

// UpstreamConversationIDNotIn applies the NotIn predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldUpstreamConversationID, vs...))
}

// UpstreamConversationIDGT applies the GT predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDGTE applies the GTE predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDLT applies the LT predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDLTE applies the LTE predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDContains applies the Contains predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDHasPrefix applies the HasPrefix predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDHasSuffix applies the HasSuffix predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDIsNil applies the IsNil predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDIsNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIsNull(FieldUpstreamConversationID))
}

// UpstreamConversationIDNotNil applies the NotNil predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDNotNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotNull(FieldUpstreamConversationID))
}

// UpstreamConversationIDEqualFold applies the EqualFold predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldUpstreamConversationID, v))
}

// UpstreamConversationIDContainsFold applies the ContainsFold predicate on the "upstream_conversation_id" field.
func UpstreamConversationIDContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldUpstreamConversationID, v))
}

// UpstreamSessionIDEQ applies the EQ predicate on the "upstream_session_id" field.
func UpstreamSessionIDEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDNEQ applies the NEQ predicate on the "upstream_session_id" field.
func UpstreamSessionIDNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDIn applies the In predicate on the "upstream_session_id" field.
func UpstreamSessionIDIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldUpstreamSessionID, vs...))
}

// UpstreamSessionIDNotIn applies the NotIn predicate on the "upstream_session_id" field.
func UpstreamSessionIDNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldUpstreamSessionID, vs...))
}

// UpstreamSessionIDGT applies the GT predicate on the "upstream_session_id" field.
func UpstreamSessionIDGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDGTE applies the GTE predicate on the "upstream_session_id" field.
func UpstreamSessionIDGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDLT applies the LT predicate on the "upstream_session_id" field.
func UpstreamSessionIDLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDLTE applies the LTE predicate on the "upstream_session_id" field.
func UpstreamSessionIDLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDContains applies the Contains predicate on the "upstream_session_id" field.
func UpstreamSessionIDContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDHasPrefix applies the HasPrefix predicate on the "upstream_session_id" field.
func UpstreamSessionIDHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDHasSuffix applies the HasSuffix predicate on the "upstream_session_id" field.
func UpstreamSessionIDHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDIsNil applies the IsNil predicate on the "upstream_session_id" field.
func UpstreamSessionIDIsNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIsNull(FieldUpstreamSessionID))
}

// UpstreamSessionIDNotNil applies the NotNil predicate on the "upstream_session_id" field.
func UpstreamSessionIDNotNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotNull(FieldUpstreamSessionID))
}

// UpstreamSessionIDEqualFold applies the EqualFold predicate on the "upstream_session_id" field.
func UpstreamSessionIDEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldUpstreamSessionID, v))
}

// UpstreamSessionIDContainsFold applies the ContainsFold predicate on the "upstream_session_id" field.
func UpstreamSessionIDContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldUpstreamSessionID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldProvider, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldTitle, v))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldRequestedModel, v))
}

// CapabilityModeEQ applies the EQ predicate on the "capability_mode" field.
func CapabilityModeEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldCapabilityMode, v))
}

// CapabilityModeNEQ applies the NEQ predicate on the "capability_mode" field.
func CapabilityModeNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldCapabilityMode, v))
}

// CapabilityModeIn applies the In predicate on the "capability_mode" field.
func CapabilityModeIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldCapabilityMode, vs...))
}

// CapabilityModeNotIn applies the NotIn predicate on the "capability_mode" field.
func CapabilityModeNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldCapabilityMode, vs...))
}

// CapabilityModeGT applies the GT predicate on the "capability_mode" field.
func CapabilityModeGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldCapabilityMode, v))
}

// CapabilityModeGTE applies the GTE predicate on the "capability_mode" field.
func CapabilityModeGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldCapabilityMode, v))
}

// CapabilityModeLT applies the LT predicate on the "capability_mode" field.
func CapabilityModeLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldCapabilityMode, v))
}

// CapabilityModeLTE applies the LTE predicate on the "capability_mode" field.
func CapabilityModeLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldCapabilityMode, v))
}

// CapabilityModeContains applies the Contains predicate on the "capability_mode" field.
func CapabilityModeContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldCapabilityMode, v))
}

// CapabilityModeHasPrefix applies the HasPrefix predicate on the "capability_mode" field.
func CapabilityModeHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldCapabilityMode, v))
}

// CapabilityModeHasSuffix applies the HasSuffix predicate on the "capability_mode" field.
func CapabilityModeHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldCapabilityMode, v))
}

// CapabilityModeEqualFold applies the EqualFold predicate on the "capability_mode" field.
func CapabilityModeEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldCapabilityMode, v))
}

// CapabilityModeContainsFold applies the ContainsFold predicate on the "capability_mode" field.
func CapabilityModeContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldCapabilityMode, v))
}

// HistoryModeEQ applies the EQ predicate on the "history_mode" field.
func HistoryModeEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldHistoryMode, v))
}

// HistoryModeNEQ applies the NEQ predicate on the "history_mode" field.
func HistoryModeNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldHistoryMode, v))
}

// HistoryModeIn applies the In predicate on the "history_mode" field.
func HistoryModeIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldHistoryMode, vs...))
}

// HistoryModeNotIn applies the NotIn predicate on the "history_mode" field.
func HistoryModeNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldHistoryMode, vs...))
}

// HistoryModeGT applies the GT predicate on the "history_mode" field.
func HistoryModeGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldHistoryMode, v))
}

// HistoryModeGTE applies the GTE predicate on the "history_mode" field.
func HistoryModeGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldHistoryMode, v))
}

// HistoryModeLT applies the LT predicate on the "history_mode" field.
func HistoryModeLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldHistoryMode, v))
}

// HistoryModeLTE applies the LTE predicate on the "history_mode" field.
func HistoryModeLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldHistoryMode, v))
}

// HistoryModeContains applies the Contains predicate on the "history_mode" field.
func HistoryModeContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldHistoryMode, v))
}

// HistoryModeHasPrefix applies the HasPrefix predicate on the "history_mode" field.
func HistoryModeHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldHistoryMode, v))
}

// HistoryModeHasSuffix applies the HasSuffix predicate on the "history_mode" field.
func HistoryModeHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldHistoryMode, v))
}

// HistoryModeEqualFold applies the EqualFold predicate on the "history_mode" field.
func HistoryModeEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldHistoryMode, v))
}

// HistoryModeContainsFold applies the ContainsFold predicate on the "history_mode" field.
func HistoryModeContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldHistoryMode, v))
}

// CachePolicyEQ applies the EQ predicate on the "cache_policy" field.
func CachePolicyEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldCachePolicy, v))
}

// CachePolicyNEQ applies the NEQ predicate on the "cache_policy" field.
func CachePolicyNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldCachePolicy, v))
}

// CachePolicyIn applies the In predicate on the "cache_policy" field.
func CachePolicyIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldCachePolicy, vs...))
}

// CachePolicyNotIn applies the NotIn predicate on the "cache_policy" field.
func CachePolicyNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldCachePolicy, vs...))
}

// CachePolicyGT applies the GT predicate on the "cache_policy" field.
func CachePolicyGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldCachePolicy, v))
}

// CachePolicyGTE applies the GTE predicate on the "cache_policy" field.
func CachePolicyGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldCachePolicy, v))
}

// CachePolicyLT applies the LT predicate on the "cache_policy" field.
func CachePolicyLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldCachePolicy, v))
}

// CachePolicyLTE applies the LTE predicate on the "cache_policy" field.
func CachePolicyLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldCachePolicy, v))
}

// CachePolicyContains applies the Contains predicate on the "cache_policy" field.
func CachePolicyContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldCachePolicy, v))
}

// CachePolicyHasPrefix applies the HasPrefix predicate on the "cache_policy" field.
func CachePolicyHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldCachePolicy, v))
}

// CachePolicyHasSuffix applies the HasSuffix predicate on the "cache_policy" field.
func CachePolicyHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldCachePolicy, v))
}

// CachePolicyEqualFold applies the EqualFold predicate on the "cache_policy" field.
func CachePolicyEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldCachePolicy, v))
}

// CachePolicyContainsFold applies the ContainsFold predicate on the "cache_policy" field.
func CachePolicyContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldCachePolicy, v))
}

// SyncStatusEQ applies the EQ predicate on the "sync_status" field.
func SyncStatusEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldSyncStatus, v))
}

// SyncStatusNEQ applies the NEQ predicate on the "sync_status" field.
func SyncStatusNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldSyncStatus, v))
}

// SyncStatusIn applies the In predicate on the "sync_status" field.
func SyncStatusIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldSyncStatus, vs...))
}

// SyncStatusNotIn applies the NotIn predicate on the "sync_status" field.
func SyncStatusNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldSyncStatus, vs...))
}

// SyncStatusGT applies the GT predicate on the "sync_status" field.
func SyncStatusGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldSyncStatus, v))
}

// SyncStatusGTE applies the GTE predicate on the "sync_status" field.
func SyncStatusGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldSyncStatus, v))
}

// SyncStatusLT applies the LT predicate on the "sync_status" field.
func SyncStatusLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldSyncStatus, v))
}

// SyncStatusLTE applies the LTE predicate on the "sync_status" field.
func SyncStatusLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldSyncStatus, v))
}

// SyncStatusContains applies the Contains predicate on the "sync_status" field.
func SyncStatusContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldSyncStatus, v))
}

// SyncStatusHasPrefix applies the HasPrefix predicate on the "sync_status" field.
func SyncStatusHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldSyncStatus, v))
}

// SyncStatusHasSuffix applies the HasSuffix predicate on the "sync_status" field.
func SyncStatusHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldSyncStatus, v))
}

// SyncStatusEqualFold applies the EqualFold predicate on the "sync_status" field.
func SyncStatusEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldSyncStatus, v))
}

// SyncStatusContainsFold applies the ContainsFold predicate on the "sync_status" field.
func SyncStatusContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldSyncStatus, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldStatus, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotNull(FieldLastSyncedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.FieldNotNull(FieldDeletedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIWebThread) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIWebThread) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIWebThread) predicate.OpenAIWebThread {
	return predicate.OpenAIWebThread(sql.NotPredicates(p))
}
